-- =============================================================================
-- DAVE RPG Engine — Schema Migration: v9 → v10
-- schema/migrations/migrate_v9_to_v10.sql
--
-- Developed with the assistance of Claude (model: claude-sonnet-4-6, Anthropic)
--
-- Item location redesign: unified three-way FK replaces split tables
-- -----------------------------------------------------------------------
--
-- v9 problem: item location was split across two mechanisms:
--   - item.current_location_id (FK → location): item is at a place
--   - character_item (join table): item is held by a character
-- This required application-layer enforcement of the invariant that an item
-- belongs to exactly one place, and made container support (item inside item)
-- impossible without a third mechanism.
--
-- v10 solution: three nullable FK columns on item, exactly one of which must
-- be non-null. A CHECK constraint enforces this at the DB layer.
--
--   loc_id  → location  : item is at a location (floor, worktable, etc.)
--   char_id → character : item is carried or worn by a character
--   item_id → item      : item is inside another item (container contents)
--
-- A free-text location_description records where within the container/location/
-- character the item sits ("buried in the bottom of the pack", "tucked under
-- one arm"). This is generated by Pass 2 whenever an item is moved and
-- replaces it on every transfer — it always reflects the current position.
--
-- A slot text field records the carrying position for character-held items
-- ("right_hand", "worn", "in_pack"). This is descriptive only — no uniqueness
-- constraint. Slot exclusivity for genuinely exclusive positions (right_hand,
-- left_hand, etc.) is adjudicated by the engine and LLM, not enforced by the
-- schema. "worn" and "in_pack" are categories that naturally accept multiples.
--
-- Container hierarchy is resolved at query time via a recursive CTE — moving
-- a container does not cascade-update its contents. Depth-1 visibility is the
-- default; "search room" / "open container" triggers the full recursive query.
--
-- Confirmed flag: is_confirmed stays. When an item moves to a location via
-- item_transfers (player drops it), the engine sets is_confirmed = 1 — the
-- player placed it deliberately and knows it is there.
--
-- Migration notes:
--   SQLite does not support DROP COLUMN (pre-3.35) or ALTER TABLE ... DROP
--   CONSTRAINT. We recreate the item table to add the new columns and CHECK
--   constraint, and drop character_item entirely. Existing item rows have their
--   current_location_id preserved as loc_id; any character_item rows are
--   migrated to char_id + slot on the item row before character_item is dropped.
--
-- Usage:
--   sqlite3 <module>.db < schema/migrations/migrate_v9_to_v10.sql
-- =============================================================================

PRAGMA foreign_keys = OFF;   -- required while recreating tables with FKs


-- =============================================================================
-- Step 1: Create the new item table as item_new
-- =============================================================================

CREATE TABLE item_new (
    id          INTEGER PRIMARY KEY,
    game_id     INTEGER NOT NULL REFERENCES game(id),

    -- Natural language name and description. The LLM reasons about item
    -- behaviour from description + properties; no rigid type taxonomy needed.
    -- description is nullable for player-claimed items not yet fully described.
    name        TEXT    NOT NULL,
    description TEXT,

    -- Location relationship — exactly one of these three must be non-null.
    -- Enforced by the CHECK constraint below.
    --
    --   loc_id  : item is at a location (lying on a table, on the floor, etc.)
    --   char_id : item is carried or worn by a character
    --   item_id : item is inside another item (container contents)
    --
    loc_id      INTEGER REFERENCES location(id),
    char_id     INTEGER REFERENCES character(id),
    item_id     INTEGER REFERENCES item_new(id),

    -- Where within the location / character / container the item sits.
    -- Generated by Pass 2 on every transfer; always reflects the current
    -- position. Examples: "sitting on the worktable", "buried in the bottom
    -- of the pack", "held loosely in the right hand", "tucked under one arm".
    location_description TEXT,

    -- How the character is carrying or wearing this item (character-held items
    -- only; NULL when loc_id or item_id is set). Descriptive, not enforced for
    -- exclusivity — "worn" and "in_pack" are categories that accept multiples;
    -- "right_hand" / "left_hand" exclusivity is adjudicated at the engine layer.
    -- Examples: "right_hand", "left_hand", "worn", "in_pack", "carried"
    slot        TEXT,

    -- Tool/material quality: 0.0 (poor) to 1.0 (exceptional).
    -- Raises the execution ceiling for creative actions without raising the
    -- underlying skill float. Poor tools constrain even high skill.
    -- NULL means quality is not applicable or not yet determined.
    quality     REAL    CHECK(quality IS NULL OR quality BETWEEN 0.0 AND 1.0),

    -- Whether this item is currently visible in its location.
    -- Hidden items exist in the world but require discovery before interaction.
    is_visible  INTEGER NOT NULL DEFAULT 1
        CHECK(is_visible IN (0, 1)),

    -- Arbitrary module-specific properties as a JSON object. The LLM reasons
    -- about item behaviour from description + properties; no boolean flags needed.
    -- Examples: {"weight": "light", "container": true, "capacity": "small"}
    --           {"material": "silk", "condition": "well-mended", "readable": true}
    properties  TEXT NOT NULL DEFAULT '{}',

    -- Whether this item has been confirmed as real by Pass 2, or is a player
    -- claim awaiting adjudication. 1 = confirmed (default); 0 = claimed but
    -- not yet confirmed. Items dropped at a location via item_transfers are
    -- always set to 1 — the player placed them deliberately.
    is_confirmed INTEGER NOT NULL DEFAULT 1
        CHECK(is_confirmed IN (0, 1)),

    created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT    NOT NULL DEFAULT (datetime('now')),

    -- Exactly one location relationship must be set at all times.
    -- Table-level CHECK must appear after all column definitions (SQLite requirement).
    CHECK (
        (loc_id  IS NOT NULL) +
        (char_id IS NOT NULL) +
        (item_id IS NOT NULL) = 1
    )
);


-- =============================================================================
-- Step 2: Migrate existing item rows
--   - current_location_id → loc_id  (for location-resident items)
--   - character_item rows  → char_id + slot  (for character-held items)
-- =============================================================================

-- Location-resident items: copy across with loc_id set.
INSERT INTO item_new (
    id, game_id, name, description,
    loc_id, char_id, item_id,
    location_description, slot,
    quality, is_visible, properties, is_confirmed,
    created_at, updated_at
)
SELECT
    i.id, i.game_id, i.name, i.description,
    i.current_location_id, NULL, NULL,
    NULL, NULL,
    i.quality, i.is_visible, i.properties, i.is_confirmed,
    i.created_at, i.updated_at
FROM item i
WHERE i.current_location_id IS NOT NULL;

-- Character-held items: set char_id and slot from character_item.
INSERT INTO item_new (
    id, game_id, name, description,
    loc_id, char_id, item_id,
    location_description, slot,
    quality, is_visible, properties, is_confirmed,
    created_at, updated_at
)
SELECT
    i.id, i.game_id, i.name, i.description,
    NULL, ci.character_id, NULL,
    NULL, ci.slot,
    i.quality, i.is_visible, i.properties, i.is_confirmed,
    i.created_at, i.updated_at
FROM item i
JOIN character_item ci ON ci.item_id = i.id;


-- =============================================================================
-- Step 3: Drop old tables, rename item_new → item
-- =============================================================================

DROP TABLE character_item;
DROP TABLE item;
ALTER TABLE item_new RENAME TO item;


-- =============================================================================
-- Step 4: Re-enable foreign keys and record schema version
-- =============================================================================

PRAGMA foreign_keys = ON;

INSERT INTO schema_version (version, description)
VALUES (10, 'v10: unified item location (loc_id/char_id/item_id + CHECK); drop character_item; add location_description and slot on item; enables item_transfers outcome field');
